# This is a basic workflow to help you get started with Actions

name: Push to GitLab with SSH

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: git fetch --unshallow origin

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: bash
        run: |
          mkdir -p ~/.ssh
          cat << EOF > ~/.ssh/id_ed25519
          ${{ secrets.SSH_KEY }}
          EOF
          cat << EOF > ~/.ssh/config
          Host gitlab.com
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
          EOF
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_ed25519
          git remote rename origin old-origin
          git remote add origin git@gitlab.com:FossPrime/www-cowsay-on-nix.git
          git push --set-upstream origin --all
